# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microshop

resources:
  - namespace.yaml
  - mongodb/statefulset.yaml
  - mongodb/headless-service.yaml
  - mongodb/mongodb-secret.yaml
  - redis/statefulset.yaml
  - redis/headless-service.yaml
  - redis/secret.yaml
  - product-service/deployment.yaml
  - product-service/service.yaml
  - product-service/configmap.yaml
  - order-service/deployment.yaml
  - order-service/service.yaml
  - order-service/secrets.yaml
  - ingress/ingress.yaml